name: Verify cross-compilation on OpenWrt environment
on: [push]


jobs:

  cross-compile:
    runs-on: ubuntu-latest
    container: fdekeers/openwrt_tl-wdr4900_gha

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Install Python packages
        run: pip install -r $GITHUB_WORKSPACE/requirements.txt

      - name: Translate and build profiles, with binary verdict
        run: $GITHUB_WORKSPACE/.ci_scripts/cross-compile/translate_and_build.sh

      - name: Translate and build profiles, with rate limiting verdict
        run: $GITHUB_WORKSPACE/.ci_scripts/cross-compile/translate_and_build.sh -r 50

      - name: Translate and build profiles, with stochastic verdict
        run: $GITHUB_WORKSPACE/.ci_scripts/cross-compile/translate_and_build.sh -p 0.5
