name: Verify cross-compilation on OpenWrt environment
on: [push]


jobs:

  cross-compile:
    runs-on: ubuntu-latest
    container: fdekeers/openwrt_tl-wdr4900_gha

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Install Python packages
        run: pip install -r $GITHUB_WORKSPACE/requirements.txt

      - name: Translate profiles
        run: $GITHUB_WORKSPACE/.ci_scripts/firewall-test/translate_profiles.sh

      - name: Run cross-compilation
        run: $GITHUB_WORKSPACE/build.sh -d $GITHUB_WORKSPACE -t $GITHUB_WORKSPACE/openwrt/tl-wdr4900.cmake
